added sorting to event handlers
FRINXio/frinx-inventory-server pull request #338
Opened 2023-08-07 15:08 UTC by plehocky

https://frinxhelpdesk.atlassian.net/browse/FD-566?atlOrigin=eyJpIjoiZGVlODdlMWU0MWZhNDU0Y2E2ZmU0OTM1MWJhZDA1NDEiLCJwIjoiaiJ9

Added sorting to event handler page
Test with frontend branch `add-filter-pagination-to-event-handlers`

2023-08-09 13:14 UTC, MarcoMruz requested changes

2023-08-09 13:14 UTC, MarcoMruz commented on src/schema/api.graphql
> +  actions
actions should not be sortable since this property is array of objects and we do not have logic for it on how to sort it and also based on what property should we sort. Since we show only three types of actions. In my opinion it is not added value for the end user

2023-08-10 12:01 UTC, MarcoMruz approved these changes

2023-08-14 07:47 UTC, soson commented on src/schema/api.graphql
> +    orderBy: EventHandlersOrderByInput!
orderBy should be optional parameter

2023-08-14 10:51 UTC, soson approved these changes

2023-08-14 12:45 UTC, merged